### PR TITLE
Added 9. Avoid mass messages

### PR DESCRIPTION
**Pull request by MarkusGordathian**

### CODE REVIEW

**Comment by meew0** [comment]
Is there any particular reason you're proposing this change? What, in your opinion, is wrong with mass announcement PMs?

**Comment by MarkusGordathian** [comment]
Mass announcement messages/PMs are disorganized and possibly annoying. A home server serves as one place where people can choose to receive announcements and support for a bot.

**Comment by meew0** [comment]
I've always seen mass announcements as somewhat necessary; while a help server is likely a cleaner solution, you won't reach every user of your bot because not everyone wants another server to clutter their list. I agree that they are possibly annoying but I wouldn't see them as more annoying than announcements on a help server - you'll get a PM or mention either way, how does it matter where?

**Comment by Thunder33345** [comment]
I would think it is reasonable to only be PMed for server owners/moderators
as it is not really necessary for server user to know about the bot downtime, the mods could just relay it if it is nessary

**Comment by LoganDark** [comment]
Rather than mass PMing users, you should allow server owners to subscribe to announcements manually and then announcements will be forwarded to that channel. That is my plan for a bot that I'm developing for a friend of mine.

**Pull request closed without merging**
