### PR TITLE
Added a few other things

### PR DESCRIPTION
**Pull request by AraHaan**
I added a few other rules that would be great (yes I mean great).

### CODE REVIEW

**Comment by abalabahaha** [comment]
Better word choices and better English could be used.

**Comment by meew0** [comment]
I agree with @abalabahaha, please use correct grammar and a more formal language when making a PR.

**Comment by Guichaguri** [comment]
`do not copy from other bots unless their code is on github.`
Being on Github or not, you can only copy from other bots if their licenses let you do that

**Comment by anowlcalledjosh** [comment]
>Do not make bots consisting of only 1 command and nothing else.

Why not? Assuming the bot follows the other guidelines, you can just ignore it.

**Pull request closed without merging**
