### PR TITLE
adds mention loops

### PR DESCRIPTION
**Pull request by CKing**

### CODE REVIEW

**Comment by meew0** [comment]
You've made a small mistake, in the first line, it should be "don't" with an apostrophe. Otherwise this is a good addition - any other opinions?

**Comment by RogueException** [comment]
That's a good point - and one I violate heavily with my own bot. That being said, I think it's a good idea to still include the name of the person the bot is replying to, in case two commands are run at similar times.

**Comment by CKing** [comment]
first of all, i really dislike bots who put mentions in replies. i am now avoiding things like this  
second: it still might lead to mention loops, if you do it right/wrong on purpose

**Comment by meew0** [comment]
Whoops, I forgot to merge this. Doing it now

**Pull request merged**
