### PR TITLE
Add note about respecting the Discord API

### PR DESCRIPTION
**Pull request by b1naryth1ef**
We love bots, but we hate bots that spam and misuse the API. Hopefully should help avoid some temporary IP bans for the folks that get themselves wrapped up in request loops.

### CODE REVIEW

**Comment by meew0** [comment]
You've made two small typos, there's a `"` before the closing `**` in the header, and you wrote "Discords API" instead of "Discord's API". As for the content, shouldn't the library handle the user agents and not the bot?

**Comment by b1naryth1ef** [comment]
@meew0 fixed.

**Comment by meew0** [comment]
Nice :+1: 

I'll keep this open for a day or two so other people can comment on it.

**Comment by uniquoooo** [comment]
:100:

**Comment by NelsonMinar** [comment]
Is there somewhere that documents how to handle rate limiting and backoffs? I've gotten a couple of 429 Too Many Requests responses and have no idea what to do in response to that. This doc would be the first place I look to find out.

**Comment by uniquoooo** [comment]
@NelsonMinar this is more rules for the creation of bots, if you were looking for information on the raw API you should check out the documentation or ask on the discord guild.

**Comment by b1naryth1ef** [comment]
@NelsonMinar We don't have any official document right now, but that will definitely come with the official API.

The gist is:
- Authentication routes are _heavily_ rate limited.
- Messages/Channels are rate limited, but have fairly sane limits (e.g. 10 messages every 10 seconds)
- Some guild related calls are rate limited.

The best way to handle backoff/ratelimiting is to treat 429 as a "hey, your doing this too quick, try again in a couple seconds/minutes".

**Comment by NelsonMinar** [comment]
Thanks for the info! It'd be nice to hint at this in a document, but maybe that's a lot of work right now.

BTW, while you're designing the official API, you may want to look at how the Riot API handles rate limiting. Specifically the Retry-After header in the 429 response; it tells the caller how long they should wait before trying again. I'm not sure that entirely makes sense in the websocket context, but it works well for their HTTP/REST API.

https://developer.riotgames.com/docs/rate-limiting

**Comment by uniquoooo** [comment]
That’s how it’s handled at the moment. With a 429 a Retry-After header is sent with the time to wait in milliseconds.

It’s also sent in JSON but I can’t remember the format.

**Comment by meew0** [comment]
No comments against this, so I'll merge it

**Pull request merged**
