### PR TITLE
Added 10. Don't make open eval commands

### PR DESCRIPTION
**Pull request by lepeli**

### CODE REVIEW

**Comment by meowingtwurtle** [comment]
This repo seems to be more about how bots interface with Discord and user, not how to prevent breaking/overloading your machine.

**Comment by meew0** [comment]
See above

**Comment by JayTurnr** [comment]
ELI5: open eval commands?

**Comment by Geo1088** [comment]
Interpreted languages generally have a built-in function that allows you to pass in a string and have it executed as code, e.j. Javascript:

```js
var a = 10;
eval("console.log('The number is', a)")
//> The number is 10
``` 

Bot developers sometimes include commands which take text as input, and print the output as a message; however, if this isn't restricted, it allows arbitrary code execution by users which is a huge security flaw that gives anyone with technical knowledge a degree of access to the computer running the bot.

**Comment by JayTurnr** [comment]
That's such a huge security flaw. Surely most devs aren't that stupid, right?

**Comment by Geo1088** [comment]
If you're not thinking about it, you might include it unblocked for development and then forget to remove or restrict it before moving to production... I imagine most people would be smart enough to double check it, and probably have it restricted from the start, but people just getting into development forget stuff like that easily.

**Pull request closed without merging**
