### PR TITLE
Added restriction on prefixes

### PR DESCRIPTION
**Pull request by ElianWonhalf**

### CODE REVIEW

**Comment by meew0** [comment]
Seems good, never thought of this. Any other opinions?

**Comment by aliasfalse** [comment]
Looks good to me. perhaps there could be another place to register said prefixes to be able to easily find combinations that aren't already used.

**Comment by geo1088** [comment]
@aliasfalse good luck getting every bot dev to use a tool like that. Best place to start would be the bots server, it's got a pretty big list.

**Comment by aliasfalse** [comment]
@geo1088 i totally agree, but it'd be nice. i don't necessarily mean a tool to register, just a list like this is for best practices.

**Pull request merged**
