### PR TITLE
Update prefix section for slash commands and emojis

### PR DESCRIPTION
**Pull request by DiamondMiner88**

### CODE REVIEW

**Comment by FireController1847** [comment]
Hey there, this repository is outdated and no longer maintained. I believe that we changed it appropriately but feel free to take a look on my fork :)

**Comment by DiamondMiner88** [comment]
Unfortunate since this repo has 300 stars. There's no way to contact him either

**Comment by TurnrDev** [comment]
Also, you renamed the file here...

**Comment by DiamondMiner88** [comment]
Did I? whoops, didn't even notice

**Pull request closed without merging**
