### PR TITLE
Add reuse session notice

### PR DESCRIPTION
**Pull request by Scarsz**
I shifted the other notes down a number and put this one at the top because of it's importance.

### CODE REVIEW

**Comment by meew0** [comment]
How is it more important than anything else?

**Comment by Scarsz** [comment]
Discord, if I'm not loosing it, has said they're going to rate limit the login page. Plus, being considerate to their api in the first place. Would much rather not bomb the login page for every command when you can just do it once.

**Comment by meew0** [comment]
Fair enough, but previous notes mostly focused on how bots should behave rather than be implemented. I would suggest making two separate sections, "Implementation" and "Behaviour", and moving this particular note into the "Implementation" section. Any other thoughts?

**Comment by meew0** [comment]
Closing due to inactivity

**Pull request closed without merging**
